apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: nada
  description: NAV Data
spec:
  owner: nada

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nav-data
  description: Markedsplassen for dataprodukter
spec:
  owner: nada
  domain: nada

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nada-backend
  description: An application to register and publish dataproducts, as well as to give access to dataproducts.
spec:
  type: service
  lifecycle: experimental
  owner: nada
  system: nav-data
  providesApis:
    - nada-api
  subcomponentOf: nav-data
    
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nada-frontend
  description: An application to register and publish dataproducts, as well as to give access to dataproducts.
spec:
  type: website
  lifecycle: experimental
  owner: nada
  system: nav-data
  consumesApis:
    - nada-api
  subcomponentOf: nav-data

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: nada-api
  description: OpenAPI Spec for NADA
spec:
  type: graphql
  lifecycle: experimental
  owner: nada
  system: nav-data
  definition:
    _queryType: Query
    _mutationType: Mutation
    _subscriptionType:
    _directives:
    - "@authenticated"
    - "@deprecated"
    - "@goField"
    - "@goModel"
    - "@include"
    - "@skip"
    _typeMap:
      Access: Access
      BigQuery: BigQuery
      BigQueryTable: BigQueryTable
      BigQueryType: BigQueryType
      Boolean: Boolean
      Collection: Collection
      CollectionElement: CollectionElement
      CollectionElementType: CollectionElementType
      Dataproduct: Dataproduct
      Datasource: Datasource
      Float: Float
      GCPProject: GCPProject
      Group: Group
      ID: ID
      Int: Int
      Mutation: Mutation
      NewBigQuery: NewBigQuery
      NewCollection: NewCollection
      NewDataproduct: NewDataproduct
      Owner: Owner
      Query: Query
      SearchQuery: SearchQuery
      SearchResult: SearchResult
      String: String
      SubjectType: SubjectType
      TableColumn: TableColumn
      Time: Time
      UpdateCollection: UpdateCollection
      UpdateDataproduct: UpdateDataproduct
      UserInfo: UserInfo
      __Schema: __Schema
      __Type: __Type
      __TypeKind: __TypeKind
      __Field: __Field
      __InputValue: __InputValue
      __EnumValue: __EnumValue
      __Directive: __Directive
      __DirectiveLocation: __DirectiveLocation
    _subTypeMap: {}
    _implementationsMap: {}

